services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend
    container_name: django_backend
    command: [ 'gunicorn', 'backend.wsgi:application', '--bind', '0.0.0.0:8000' ]
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backend:/app
      - /app/venv
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - '3000:3000'
      - '5001:5000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000
volumes:
  postgres_data: